cmd/hhfab/main.go
pkg/fab/wiring/builder.go
pkg/fab/wiring/hydrate.go

Virtual External config is generated based on last orphan leaf in the wiring diagram, so at least one orphan leaf is mandatory.

[vlab] Generate virtual external config

---

pkg/fab/recipe/flatcar/control_os_install.go

In an installed flatcar image, the root partition is ~2GB. This is too small for our control-os install files. So we are making the installed root partition bigger, sizing up to 9GB. So we can fit all of our install materials. When flatcar runs its first boot scripts it will resize the partition to fit the whole disk.

Expand root partition size

---

pkg/fab/recipe/control_build_usb.go

Additional context is provided in the longer commit messages. I am adding them here for visibility:
- go-diskfs makes the 512 byte sector size assumption in a lot of places FAT does as well. Best to stay at 512
- The partition labels don't need to match the filesystem labels, so we are okay to keep them. Additionally it is helpful to to see our disk in the output of lsblk

Resolve todos

---

pkg/fab/recipe/flatcar/control_os_install.go

nvme drives add `p9` to the partition name not a simple 9. 
Fixes #209

Nvme partition name

---

pkg/fab/README.md
pkg/fab/versions.go

@cesargithedgehog prepared new fd files for onie with 
```
DEFINE NETWORK_SNP_ENABLE       = FALSE
DEFINE NETWORK_IP6_ENABLE       = FALSE
DEFINE NETWORK_TLS_ENABLE       = FALSE
DEFINE NETWORK_HTTP_BOOT_ENABLE = FALSE
DEFINE NETWORK_HTTP_ENABLE      = FALSE
DEFINE NETWORK_ISCSI_ENABLE     = FALSE
DEFINE SECURE_BOOT_ENABLE       = FALSE
```

Switch onie-vlab to the version without net boot

---

cmd/hhfab/main.go
pkg/hhfab/testing.go

With `-P 4` it's WAY more stable on all 3 envs (env-1/2/3) and hitting ~9300 Mbps very reliably while it wasn't hitting 8000 all the time previously. Additionally rising default to 8500.

Run iperf with 4 threads to get more stable numbers

---

pkg/hhfab/vlabhelpers.go

Small PR to prettify the output of `vlab switch seriallog` adding `-r` option to `less`
Before:
After:

make seriallog output more readable

---

pkg/hhfab/vlab_butane.tmpl.yaml

Enables LLDP on server VM interfaces to cross-check topology:
```
core@server-1 ~ $ networkctl -l lldp 
LINK   CHASSIS-ID        SYSTEM-NAME CAPS        PORT-ID   PORT-DESCRIPTION                                      
enp2s1 54:bf:64:ba:3d:c0 s5248-01    ....r...... Ethernet1 PC2 MCLAG server-1 server-1--mclag--s5248-01--s5248-02
enp2s2 3c:2c:30:66:f0:00 s5248-02    ....r...... Ethernet1 PC2 MCLAG server-1 server-1--mclag--s5248-01--s5248-02
Capability Flags:
r - Router
2 neighbors listed.
```
Also enables DHCP on the same interfaces

Enable LLDP on Server VMs

---

pkg/hhfab/vlab_butane.tmpl.yaml

Adds script and one-shot service to Butane template to disable LLDP agent for NICs found under /sys/kernel/debug/i40e/
As the NICs are in passthrough mode for the VMs, the embedded LLDP agent is interfering with the Fabric LLDP
Solves #296

Disable LLDP agent on Server VM XL710 NICs

---

pkg/hhfab/vlabhelpers.go
pkg/hhfab/vlabhelpers_reinstall.exp

It will only show to the user in case reinstall is verbose indeed
Expect helper has now the verbose support

Invoke reinstall helper verbose by default

---

pkg/hhfab/show-tech/control.sh
pkg/hhfab/show-tech/server.sh
pkg/hhfab/show-tech/switch.sh
pkg/hhfab/vlabhelpers.go

I have added more show commands and refactored the shell scripts
Also had to increase timeout as it takes a bit longer but it gets tons useful information

Extend and refactor show-tech scripts

---

.github/workflows/ci.yaml

It should make all uploaded artifacts sortable to group things by job/stage and easier to navigate.

ci: use slugs and upload reg logs

---

.github/workflows/ci.yaml

Seems like we're facing issues caused by switches time getting out of sync over time due to the upstream NTP server not being reacheable from the control node (and so strata is too high).

ci: make controls unrestricted so ntp upstream works

---

pkg/hhfab/vlabhelpers_reinstall.exp

Required to reinstall NOS for the ds4101

fix(reinstall): increase ONIE Service Discovery timeout for ds4101

---

pkg/hhfab/testing.go

and retry up to 10 times if not.
Fixes: #310

fix(testing): check if iperf server is up/reachable

---

pkg/hhfab/cmddiagram.go
pkg/hhfab/diagram/drawio.go
pkg/hhfab/diagram/graphviz.go
pkg/hhfab/diagram/mermaid.go
pkg/hhfab/diagram/types.go

The reported name VS the file saved were not matching. Now it is fixed:
```
pau@fedora:~/fabricator$ bin/hhfab diagram
18:06:10 INF Hedgehog Fabricator version=v0.36.0-dirty-bv1751
18:06:10 INF Generated draw.io diagram file=result/diagram.drawio style=default
To use this diagram:
1. Open with https://app.diagrams.net/ or the desktop Draw.io application
2. You can edit the diagram and export to PNG, SVG, PDF or other formats
pau@fedora:~/fabricator$ ls result/
diagram.drawio
```

diagram: fix output name across formats

---

.github/workflows/ci.yaml
pkg/hhfab/release.go

* the 'Multi-Subnets with filtering' is using local peering and so can fail if subinterfaces are not supported, tag it accordingly
* the total failure count at the end of the test was wrong if some test had been skipped at execution time, due to us not resetting the error (used for the skip message) and also counting it as a failure
* curls were not being executed unless the extended flag was selected. this was intentional to reduce testing time, but it was the wrong decision, as it's the only way we actually test external peerings right now. enable them by default
* we were not importing the default prefix from externals, so we were only testing the fact that we could not curl (as expected)
* note that the contrary is true now, i.e. we always import the default prefix. It is probably …

Misc release test fixes

---

pkg/fab/README.md
pkg/fab/versions.go

bump: k3s to v1.32.3+k3s1 (currently latest in stable channel)

---

config/manager/manager.yaml

It's running over 70% mem limit, worse looking into in the future, but for now it's ok just to raise the limit to avoid OOMs.

chore: double fabricator-controller mem limits

---

pkg/fab/recipe/control_upgrade.go

It was introduced in the https://github.com/githedgehog/fabricator/commit/66454e9026bf66734f1b6d052853afd78b3a1898

fix: remove second k3s upgrade attempt

---

.github/workflows/ci.yaml

Fixes githedgehog/internal#166

ci(vlab): test upgrades from 25.02

---

pkg/hhfab/release.go

if the first test was skipped, e.g. due to a regex, the initial setup was being run twice in a row

fix: repeated initial setup in release test

---

.github/workflows/ci.yaml

same as we do for normal test connectivity, but for the release-test job
Fix #646

ci: workaround to fix ntp desync

---

pkg/hhfab/testing.go

the minimal speed is a helpful tool to detect whether physical switches are software-forwarding traffic, but for virtual switches this does not apply. often release-tests on virtual switches will fail with some iperf flow being slower than the already low limit we were setting, and we have not done anything in response to that anyway otehr than restarting the test, so stop checking for that condition.

chore: ignore iperf speed for virtual switches

---

pkg/hhfab/vlabrunner.go

Run show tech when release tests fail. Currently it is not collecting them:
https://github.com/githedgehog/fabricator/actions/runs/15806736430/job/44552621163

ci: run show tech for release tests

---

.github/workflows/ci.yaml
cmd/hhfab/main.go
justfile
pkg/hhfab/cmddiagram.go
pkg/hhfab/diagram/diagram.go
pkg/hhfab/diagram/drawio.go
pkg/hhfab/diagram/graphviz.go
pkg/hhfab/diagram/mermaid.go
pkg/hhfab/diagram/styles.go
pkg/hhfab/diagram/topology.go
pkg/hhfab/diagram/types.go
pkg/hhfab/hydrate.go

fixes some cosmetic bugs (overlapping labels) and improves diagram rendering for more complex topologies, such as 3 spine ones

Diagram enhancements

---

pkg/hhfab/release.go

the test will run and pass but there will be no servers attached to ESLAG connections, so we are just wasting time

fix(release-test): skip ESLAG failover with l3vni

---

cmd/hhfab/main.go
pkg/hhfab/release.go
pkg/hhfab/testing.go

we are already skipping servers that are not attached to any VPC as part of the checks to make test-connectivity work with ESLAG and L3VNIs. However at the moment this prints a warning re ESLAG, and it could simply be that the server has no attachment. Regardless, there are situations when someone is calling test-connectivity on a manual setup where only some servers are attached to a VPC, and it is useful to be able to do so. This PR introduces a flag (all-servers) which will make the test fail if it detects that some server has no vpc attach, and fixes the message when we skip a server due to this reason. By default the flag is not set, and tests will simply skip non-attached servers.

feat: test-connectivity flag all-servers

---

pkg/fab/recipe/node_install.go

fix: continue if node cfg image was already installed

---

pkg/hhfab/testing.go

* workaround the iperf3 server json parsing issue so that we can report the error returned and not just the exit code
* separate client and server errror messages, report both if they are not nil.
* avoid replicating twice the speed information in the message
Part of #922

chore: more iperf3 error report tweaks

---

pkg/fab/README.md

```
/tmp/t.udt0suVzly 
09:16:36 ➜  oras pull ghcr.io/githedgehog/fabricator/bash-completion:v2.16.0                       
✓ Pulled      bash-completion                                                                                                                    604/604 KB 100.00%  211ms
└─ sha256:1b924bc8e181b507bf8399a7501e35716dbf1d4d5805b2d0c750eea38ad9c717                                                                                              
✓ Pulled      application/vnd.oci.image.manifest.v1+json                                                                                         744/744  B 100.00%   53µs
└─ sha256:7c691e3dcb061ed163f24f2b68787dce1dc10d6824ce64379c86b0693c5a6330 …
```

chore: publish bash comp package

---

pkg/hhfab/release.go

It allows to avoid issues with the pipelines and any other potential issues with finding the right port for the test. We just need to test the fact that we can change a breakout, doesn't matter which mode we're going to use.
Fixes githedgehog/internal#221

fix(release): always use single resulting port breakout

---

cmd/hhfab/main.go
pkg/hhfab/release.go
pkg/hhfab/vlab_external_butane.tmpl.yaml
pkg/hhfab/vlabbuilder.go
pkg/hhfab/vlabconfig.go

Generate wirings for externals as part of hhfab vlab gen. Add parameters to determine how many externals and external connections are created, and where the ext. connections are placed (i.e. mclag, eslag or orphan leaves).
All attachments are currently vlan tagged, I didn't want to over complicate things with extra params for untagged.
Also all externals are in the same namespace, and attachments are created for all externals and all connections.
Closes: #521

vlab: generate wiring for externals

---

.github/workflows/ci.yaml

currently they are only published on success, which is pretty useless. also print individual failures for each run of the same test
part of https://github.com/githedgehog/internal/issues/220

fix(ci): always publish release-test results
