githedgehog/fabricator

cmd/hhfab/main.go

typos: proof readings of the code

---

.github/workflows/ci.yaml
hack/localreg.sh

Just use env vars from the runner itself to allow 3rd party PRs

---

pkg/hhfab/hhnet.sh

* set down interface before enslaving it, to prevent errors if it is already up
* limit the attempts in get_ip to 30 to avoid stalling forever

Minor improvs to hhnet script

---

cmd/hhfab/main.go
pkg/fab/recipe/control_build.go

Correct some usage messages and a log message

Correct some messages

---

.github/workflows/ci.yaml
cmd/hhfab/main.go
pkg/fab/recipe/control_build.go
pkg/fab/recipe/control_build_usb.go
pkg/fab/recipe/control_build_usb_butane.yaml
pkg/fab/recipe/control_butane.tmpl.yaml
pkg/fab/recipe/control_install.go
pkg/fab/versions.go
pkg/hhfab/cmdbuild.go
pkg/hhfab/cmdvlab.go
pkg/hhfab/vlabrunner.go

Add option to generate iso bootable media

---

.github/workflows/ci.yaml

Removes a harmless warming in the Actions UI
I took the opportunity to test the VLAB jobs with the soon-to-be ubuntu-latest (24.04). All good

Fix build warnings

---

pkg/hhfab/vlabhelpers.go
pkg/hhfab/vlabhelpers_reinstall.exp

Refactor vlabhelpers_reinstall.exp and improve error propagation
Fixes #317

Better switch reinstall error handling

---

pkg/hhfab/pdu/netio.go

Fixes https://github.com/githedgehog/fabricator/issues/340

Fix PDU action on-off mappings

---

pkg/hhfab/testing.go

split some of the CLI functions and expose some helpers so that a test program can call/build upon the existing code instead of having to run the executable.

hhfab: splits and helpers for testing

---

pkg/hhfab/hhnet.sh

one minute could not be sufficient

hhnet: increase dhcp timeout to 5 minutes

---

pkg/hhfab/vlabhelpers.go
pkg/hhfab/vlabhelpers_reinstall.exp

Capture some more error conditions in reinstall helper script and add verbosity to help diagnose eventual errors
Fixes #358

Improve switch reinstall error handling and verbosity

---

cmd/hhfab/main.go
pkg/hhfab/testing.go

so we can use it in demos to generate pings or traffic from specific source-destination pairs

hhfab: add src/dst filters to test-connectivity

---

cmd/hhfab/main.go
pkg/hhfab/cmdvlab.go
pkg/hhfab/diagram/drawio.go
pkg/hhfab/diagram/graphviz.go
pkg/hhfab/diagram/styles.go
pkg/hhfab/diagram/topology.go
pkg/hhfab/diagram/types.go

Adds diagram command to hhfab:
```
$ ./bin/hhfab diagram -h
NAME:
hhfab diagram - generate a diagram to visualze topology
USAGE:
hhfab diagram [command options]
OPTIONS:
--format value, -f value  diagram format: drawio (default), dot (graphviz), mermaid (unsupported) (default: "drawio")
```

Integrate diagram generation feature

---

pkg/hhfab/show-tech/control.sh
pkg/hhfab/testing.go

This PR separates the inspect retry functionality from PR #426, which address #413, which we are hitting more frequently as it seems not related to the infra

Inspect retries only

---

pkg/hhfab/release.go

it was based on the assumption of 9 servers total, but that is not necessarily true

fix: single VPC suite in release tests

---

pkg/hhfab/cmddiagram.go
pkg/hhfab/cmdvlab.go
pkg/hhfab/diagram/drawio.go
pkg/hhfab/diagram/graphviz.go
pkg/hhfab/diagram/mermaid.go
pkg/hhfab/diagram/styles.go
pkg/hhfab/diagram/topology.go
pkg/hhfab/diagram/types.go

The drawio default is good enough for now. Other formats/styles have issues

feat(diagram): add representation for gw nodes

---

pkg/hhfab/cmddiagram.go

```
ubuntu@vlab-pau:~/hhfab$ ./hhfab-diagram diagram
23:22:06 INF Hedgehog Fabricator version=v0.35.0-11-gf92da239-dirty-MZ2314
23:22:06 INF Generated draw.io diagram file=result/diagram.drawio style=default
To use this diagram:
1. Open with https://app.diagrams.net/ or the desktop Draw.io application
2. You can edit the diagram and export to PNG, SVG, PDF or other formats
ubuntu@vlab-pau:~/hhfab$ ./hhfab-diagram diagram -f dot
23:22:18 INF Hedgehog Fabricator version=v0.35.0-11-gf92da239-dirty-MZ2314
23:22:18 INF Generated graphviz diagram file=result/diagram.dot
To render this diagram with Graphviz:
1. Install Graphviz: https://graphviz.org/download/
2. Convert to PNG: dot -Tpng result/diagram.dot -o diagram.png
3. Convert to SVG: dot -Tsvg result/diagram.dot -o diagram.svg
4. Convert …
```

feat(diagram): rename diagram file and save in result folder

---

pkg/hhfab/testing.go

as we did for the iperf3 client in commit f92da23

fix(testing): retry remote cmd on ssh error

---

pkg/hhfab/testing.go

fix(vlab): wait for agent desired version to match ctrl on wait

---

pkg/hhfab/release.go

add a new flag for tests that requires subinterfaces, and skip them if any of the switches under test do not support them. note that this is a pretty ham-fisted approach, we could instead check whether the specific switch(es) that do not support them are affected by each test, but the additional complexity of the checks does not seem justified to me.
Closes: #491

feat(release-test): skip subinterfaces tests

---

pkg/hhfab/release.go

relax the skip check for subinterfaces, apply it only to leaf switches as spines are not affected

fix(release-test): subinterfaces skip for leaf only

---

pkg/hhfab/release.go

make sure that if we remove one external peering test connectivity still works fine, i.e. we are not leaking connectivity to the external

feat: extra step for all external test

---

pkg/fab/README.md
pkg/fab/versions.go
pkg/hhfab/vlabrunner.go

chore: bump flatcar to 4152.2.2

---

pkg/fab/comp/gateway/gateway.go
pkg/fab/initconfig.go
pkg/fab/initconfig_test.go
pkg/fab/recipe/control_build.go
pkg/fab/recipe/control_install.go
pkg/fab/recipe/flatcar/os_install.go
pkg/fab/recipe/install_upgrade.go
pkg/fab/versions.go
pkg/hhfab/cmdbuild.go
pkg/hhfab/cmdconfig.go
pkg/hhfab/cmdvlab.go
pkg/hhfab/hydrate.go
pkg/hhfab/vlabbuilder.go
pkg/hhfab/vlabconfig.go
pkg/hhfab/vlabhelpers.go
pkg/hhfabctl/config.go
pkg/support/kuberesources.go
pkg/util/apiutil/fab.go
pkg/util/apiutil/include.go
pkg/util/apiutil/kube.go
pkg/util/apiutil/loader.go
pkg/util/apiutil/printer.go
pkg/util/apiutil/scheme.go

Gen, hydrate and include Gateway into installer

---

pkg/hhfab/release.go

test: dhcp custom lease time in release-test

---

pkg/fab/recipe/node_install.go

Fixes githedgehog/internal#196

chore(gw): only vxlan traffic instead of all udp

---

pkg/hhfab/release.go
pkg/hhfab/testing.go

fix(release-test): derive hhnet cmd for server-1

---

pkg/hhfab/testing.go

for setup-vpcs and test-connectivity, so that we can run release-test on envs with eslag leaves.
Fix #729

fix(hhfab): skip eslag servers in l3vni mode

---

cmd/hhfab/main.go
pkg/hhfab/release.go
pkg/hhfab/testing.go

release-test: basic RoCEv2 coverage

---

pkg/hhfab/release.go
pkg/hhfab/testing.go

Address some of @Frostman comments on previous PRs

minor improvements on recent testing changes

---

pkg/fab/recipe/build.go

Increase the image size and remove magic numbers. 
closes #747

chore: increase size of usb image

---

pkg/fab/versions.go

https://github.com/githedgehog/dataplane/commit/f27f76cd91213cf4dc85d0dab95e7c70ede30efc https://github.com/githedgehog/dpdk-sys/commit/0ba323e489ea2baf3f85fc42ff23aff674a25690

bump: dp and frr to latest

---

pkg/hhfab/release.go

release-test: add coverage for port breakouts

---

pkg/hhfab/release.go

release-test: add coverage for mesh

---

pkg/hhfab/testing.go

fix: random backoff for ssh errors

---

pkg/hhfab/testing.go

So if we're so fast that one of the agent objects wasn't yet created by the fabric-controller, the wait before inspect fails immediately
https://github.com/githedgehog/fabric/actions/runs/16903382871/job/47887714632
08:49:57 INF Running on-ready command command=inspect
08:49:57 INF Inspecting fabric
08:49:57 INF Waiting for switches and gateways ready appliedFor=30s timeout=30m0s
08:49:58 INF Expected switches agent=v0-5c0f0cfc9 switches="[leaf-01 leaf-02 leaf-03]"
08:49:58 ERR Failed to wait for ready err="getting switch agent \"leaf-03\": Agent.agent.githedgehog.com \"leaf-03\" not found"
08:49:58 INF Retry attempt number=2
08:50:08 INF Retry attempt number=3

fix(test): wait should count missing agents and extra check time

---

pkg/hhfab/testing.go

an attempt to make looking at the result of test-connectivity in case of iperf3 errors slightly less cryptic

chore(testing): report iperf3 error

---

pkg/hhfab/show-tech/control.sh
pkg/hhfab/show-tech/gateway.sh
pkg/hhfab/show-tech/server.sh
pkg/hhfab/show-tech/switch.sh
pkg/hhfab/vlabhelpers.go

Trying to get more clarity on some of the current CI failures:
- https://github.com/githedgehog/fabricator/issues/925
- https://github.com/githedgehog/fabricator/issues/927

Updates in show tech

---

pkg/fab/README.md
pkg/fab/versions.go
pkg/hhfab/hhnet.sh

Adding here as a draft so we can monitor tests. Per request by @Frostman

Bump flatcar to latest stable

---

cmd/hhfab/main.go
pkg/hhfab/release.go
pkg/hhfab/testing.go

as requested by @mrbojangles3 (but I was also thinking about this for a while)

chore: add release-test list option

---

pkg/hhfab/cmdhelpers.go

fix: ensure vfio_pci driver is loaded

---

pkg/fab/README.md
pkg/fab/recipe/build.go
pkg/fab/versions.go

bump: k3s to 1.34.1

---

pkg/hhfab/vlabrunner.go
pkg/util/sshutil/easyctx.go
pkg/util/sshutil/ssh.go

feat: use context in vlab ssh lib

---

pkg/hhfab/release.go

Fix #932 
Note: the route check is not actually needed, I believe, but I'm inclined to keep it anyway - let me know if you think we should remove it (see discussion here for reference: https://github.com/githedgehog/fabricator/issues/932#issuecomment-3324023280)

release-test: static-external stability

---

pkg/fab/README.md
pkg/fab/versions.go

bump: alloy => v1.11.0

---

pkg/hhfab/release.go

fixes: https://github.com/githedgehog/internal/issues/224

fix(test): add check for empty switch for RoCE test

---

pkg/fab/README.md
pkg/fab/versions.go

fix(onie): resize image partition table
